---
projects:
  - name: crown-marketplace
    destination: applications
  - name: crown-marketplace-legacy
    destination: applications
  - name: crown-marketplace-feature-tests
    destination: testing
  - name: ccs-frontend_helpers
    destination: frontend
  - name: ccs-frontend-project
    destination: frontend
  - name: ccs-aws-codepipeline-action
    destination: misc
software:
  - name: PostgreSQL
    check_command: which psql
  - name: Redis
    check_command: which redis-server
  - name: NodeJS
    check_command: which node
  - name: Yarn
    check_command: which yarn
  - name: ClamAV
    check_command: which clamd
    optional: true
  - name: NGINX
    check_command: which nginx
