name: "Analyse code with Rubocop"

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.244.0
        with:
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop --config .runner.rubocop.yml
